spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: gang6607
    password: '{cipher}AQB8SfO/xz4pbXYtP/DRTNm7ClxV3iY0Tm1PaUmIQMvLiNBtGjDWmxM6nWpSrgFtEt7Ihv8wxIzP6BUf6A6v8+RkMhsVx9HfkpyDMXUtYc5nd5VbdH8WypfWOX3eyPxZByK2+7NM4Q85n6Hj3d6lubgTKLEq8i9xIC1ZAh0c6308K/ZndcAtCyGd6wP+QGozxURvflnIk8XXYrZHj9AvOhBmMBiHel66ibrGJpG6YKWc5876q1svwjTHtYeChRzGlBwe11GUL5LiZPmXHZW9Ji7vRqJZyAgdVdoOor427AdS2mChAlbnaToyhuyp1LA/LJrzAke+VoDSaytRIFKakSZe3GXaycLtwHDVPHj8LQDTwRakzvDIPOhZdo8+ymHEJ/0='
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

token:
  expiration_time: 3600000
  secret: 2cadded2582bbb92b7b6f9e56b66626481135cd1bfb20540a9afcdd7decde3881a611d1b8b7d0c883c1354b83a734b846cd1e2bafafcdb65b25d112708939747

gateway:
  ip: 192.168.35.8
