spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: gang6607
    password: '{cipher}AQBQdSKEF/nubJhBc24vPaG0EjCARdd/HRWYLT6CsihAtE54l2pKCYQE7iYCz6S9EcuCO/0xrU3nnBg5hQQJ2KuFbTmWiu7RPWgfcFZujCIxjD5ohoFVMzTqm8srgMLKuaft0ttfIl2dJvjsJ9SMca+IeJ9SzVlYBawcUVy089Cr8BjETCIP753lJLoVkSc1fJZxQFHnqYCJ4St6VAhbZfgi6+9C0hldbDgkAOn1YaBTCRx/ubBfLMOC2Sb0DFY3vDITATPMGq0WRik/EfRVKXpOutUGZfo8YbPcUxxmdJ7XzsiDPMc1S18CKuFZwh00Z9p9aGwvUPSyseRzSfUurp11fDvV+p0mFnEVRV02cO5V7jjc7VgoX37JuuTDdjMUqqY='
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

token:
  expiration_time: 3600000
  secret: '{cipher}AQAhfbFn2QFNO81UewkLtcBloUMyUdD6nXiEVSLNum4V0D5YQXXHC5umMhZeY2PnydQkxcfIEDyXjUhlWyKXqZJzTi2nPUHw4dMKQtsDJJ7XuYw3t9af9wHpQuSD1lWC6wJJqcCIn0TYVSr405UVHWhWg1H88z7MGN1G+ybGF7ec2PAOX+dPSzMk3XjLJzIMi+1IOIA3kaRXHd9UCq9Z8XFl7tOa30CwCwrgUgBdAQ3MpGQRFXf4oB9wwcBQFx3j37z1myrqRUA6XCx1+LTmEMEVhTHiAz90oyYJ8rMzT1LyxUB5wutaad6zpcT7EO20afd2VzGzhHPIr+53g5TbzJRa/Jk+Wz+K8dXotT9Xf+AxebRHQ4xIFTHsz0qVPJcZgDt1dJ4KzodyxpYnJ/aDT8FIrM1UCCMDiSwrSQndYHj4PHfCrmfs86GuKQaMu8VKzVKkJqgP2oEklRSsw4Hli9RbAuWkluyMFgv7N6jDXvmmYZkf3540X+G7F+92742n9//TegaNpMgoL6njHMAEo1+H'

gateway:
  #  ip: 192.168.35.8
  ip: 127.0.0.1
  port: 8000

order-service:
  url: /order-service
  get-orders: /orders
